### PR TITLE
Be smart about group by key. Resolves #27 

### LINKED ISSUE #27: Be smart about groupBy(Key)
- What is wrong with groupBy*.
- Why not all gropuBy\* are equal.
- Why naive implementations will only make things worse.
- When groupBy\* is the right choice.

### PR DESCRIPTION
**Pull request by zero323**
I think it needs more practical examples but I leave it to you @eliasah

### CODE REVIEW

**Comment by eliasah** [comment]
I've reviewed the new paragraphs, there is some sentence that I believe should be discussed. e.g : 

> The first problem we have to address in unacceptable complexity of the map-side combine

There is also some typos mainly in this [paragraph](https://github.com/awesome-spark/spark-gotchas/blob/b39caf3cd8bde8ab863b325545eddd632b1500e7/04_rdd_actions_and_transformations_by_example.md#when-to-avoid-groupbykey).

I like the skeletons of the [last paragraphs](https://github.com/awesome-spark/spark-gotchas/blob/9a1104b3768039b09b34c71d231f08a3d0e93d68/04_rdd_actions_and_transformations_by_example.md#when-to-use-groupbykey-and-when-to-avoid-it). They might need some examples, I'll try to see if I can work on a example for `repartitionAndSortWithinPartitions`.

What do you think ?

**Comment by zero323** [comment]
Sounds good. For `repartitionAndSortWithinPartitions` we you could use exact quantiles by key as an example. It is nice and easy to understand I think.

**Comment by eliasah** [comment]
So should we merge this and re-iterate on it ?

**Comment by zero323** [comment]
I slightly prefer merging, especially if you cannot commit to any particular deadline.

**Comment by eliasah** [comment]
I'm merging this. I'm very happy with the contents.

**Pull request merged**
