### PR TITLE
Window functions

### PR DESCRIPTION
**Pull request by zero323**
This is only a quick overview but I think we can merge it for now.

### CODE REVIEW

**Comment by zero323** [comment]
@eliasah Just a friendly reminder :)

**Comment by eliasah** [comment]
Why is the window function section under DataFrame by example ? I think that it needs a separate chapter. Don't you think ?

**Comment by zero323** [comment]
I don't think there is any point in organizing this right now. We can easily move things around when there is so content and I don't really know what should go to DF by example so I keep SQL stuff in a single place.

**Comment by eliasah** [comment]
Ok. No problem. I'll try to finish this by tomorrow noon the latest.

**Comment by eliasah** [comment]
This looks ok to me. But we'll need to re-organize sections later. I still believe this doesn't fit in this section.

**Pull request merged**
