### PR TITLE
Describe JDBC reader behavior when called without providing partitioning data.

### PR DESCRIPTION
**Pull request by zero323**
This work in progress for now.

### CODE REVIEW

**Comment by eliasah** [comment]
So what do we do with this for now ?

**Comment by zero323** [comment]
Just keep it open. I'll remove WIP when I think it useful enough and ping you.

**Comment by eliasah** [comment]
Agreed.

**Comment by eliasah** [comment]
What about the content of my answer here http://stackoverflow.com/a/40302758/3415409 to complete this section ?

**Comment by zero323** [comment]
To be fair I want something more comprehensive and reproducible. Also I believe that is important to point out that using JDBC connection for bulk imports (exports as well) is just not a good idea.

**Review by eliasah — APPROVED** [review]

**Pull request merged**
